[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "projeto-dl-backend"
version = "0.1.0"
description = "Backend FastAPI do PROJETO DL"
requires-python = ">=3.11"
authors = [{name = "DL Auto Pe√ßas"}]